import SwiftUI

struct JSONInputConfig {
    let sectionLabel: String
    let detectXML: Bool
    let editorMinHeight: CGFloat

    static let messageBody = JSONInputConfig(sectionLabel: "Message Body", detectXML: true, editorMinHeight: 180)
    static let eventPattern = JSONInputConfig(sectionLabel: "Event Pattern (JSON)", detectXML: false, editorMinHeight: 200)
    static let eventDetail = JSONInputConfig(sectionLabel: "Detail (JSON)", detectXML: false, editorMinHeight: 200)
    static let targetInput = JSONInputConfig(sectionLabel: "Input (optional JSON)", detectXML: false, editorMinHeight: 120)
    static let parameterValue = JSONInputConfig(sectionLabel: "Parameter Value", detectXML: false, editorMinHeight: 150)
    static let executionInput = JSONInputConfig(sectionLabel: "Input (JSON)", detectXML: false, editorMinHeight: 200)
}

struct JSONInputSection: View {
    @Binding var text: String
    @Binding var isHelperShown: Bool
    let config: JSONInputConfig

    @State private var jsonHelperText = ""
    @State private var jsonHelperParseError: String?
    @State private var showExamplePopover = false
    @AppStorage(AppPreferences.doubleClickHidesJsonHelperKey) private var doubleClickHidesJsonHelper = false
    @AppStorage(AppPreferences.disableJsonHelperPlaceholdersKey) private var disablePlaceholders = false

    var body: some View {
        Section {
            ZStack(alignment: .topLeading) {
                CodeTextEditor(text: $text, isEditable: !isHelperShown)
                    .opacity(isHelperShown ? 0.7 : 1.0)
                if text.isEmpty && isHelperShown && !disablePlaceholders {
                    Text(JSONHelperParser.defaultJSON)
                        .font(.system(.body, design: .monospaced))
                        .foregroundStyle(.placeholder)
                        .padding(.leading, 12)
                        .padding(.top, 12)
                        .allowsHitTesting(false)
                }
                if isHelperShown && doubleClickHidesJsonHelper {
                    Color.clear
                        .contentShape(Rectangle())
                        .onTapGesture(count: 2) {
                            isHelperShown = false
                        }
                }
            }
            .frame(minHeight: config.editorMinHeight)
            .background(Color(nsColor: .textBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 6))
            .overlay(
                RoundedRectangle(cornerRadius: 6)
                    .strokeBorder(Color(nsColor: .separatorColor), lineWidth: 1)
            )

            if isHelperShown {
                Text("Content is generated by the JSON Helper below. Edit the helper to update.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            jsonHelperSection
        } header: {
            sectionHeader
        }
        .onChange(of: jsonHelperText) {
            let result = JSONHelperParser.parse(jsonHelperText)
            if result.error != nil {
                jsonHelperParseError = result.error
            } else {
                jsonHelperParseError = nil
                text = result.json
            }
        }
        .onChange(of: isHelperShown) {
            if isHelperShown {
                if let helper = JSONHelperParser.fromJSON(text) {
                    jsonHelperText = helper
                }
            }
        }
    }

    // MARK: - Header

    @ViewBuilder
    private var sectionHeader: some View {
        HStack(spacing: 6) {
            Text(config.sectionLabel)
            if let type = detectedBodyType {
                Text(type)
                    .font(.caption2)
                    .fontWeight(.semibold)
                    .padding(.horizontal, 6)
                    .padding(.vertical, 2)
                    .background(bodyTypeBadgeColor(type), in: Capsule())
                    .foregroundStyle(bodyTypeForegroundColor(type))
                if type != "Text" {
                    let valid = isBodyValid(for: type)
                    HStack(spacing: 2) {
                        Image(systemName: valid ? "checkmark.circle.fill" : "xmark.circle.fill")
                            .font(.caption2)
                        Text(valid ? "Valid" : "Invalid")
                            .font(.caption2)
                            .fontWeight(.semibold)
                    }
                    .padding(.horizontal, 6)
                    .padding(.vertical, 2)
                    .background((valid ? Color.green : Color.red).opacity(0.15), in: Capsule())
                    .foregroundStyle(valid ? Color.green : Color.red)
                }
            }
            if isHelperShown {
                Text("Read-Only")
                    .font(.caption2)
                    .fontWeight(.semibold)
                    .padding(.horizontal, 6)
                    .padding(.vertical, 2)
                    .background(Color.orange.opacity(0.25), in: Capsule())
                    .foregroundStyle(.orange)
            }
        }
        .frame(height: 18, alignment: .leading)
    }

    // MARK: - JSON Helper

    @ViewBuilder
    private var jsonHelperSection: some View {
        HStack {
            if isHelperShown {
                Button {
                    showExamplePopover.toggle()
                } label: {
                    Label("Example Data", systemImage: "text.badge.star")
                        .font(.caption)
                }
                .buttonStyle(.borderless)
                .popover(isPresented: $showExamplePopover) {
                    syntaxReferencePopover
                }
            }
            Spacer()
            Button {
                isHelperShown.toggle()
            } label: {
                Label(isHelperShown ? "Hide JSON Helper" : "JSON Helper", systemImage: "curlybraces")
                    .font(.caption)
            }
            .buttonStyle(.borderless)
        }

        if isHelperShown {
            ZStack(alignment: .topLeading) {
                CodeTextEditor(text: $jsonHelperText)
                if jsonHelperText.isEmpty && !disablePlaceholders {
                    Text(JSONHelperParser.defaultExample)
                        .font(.system(.body, design: .monospaced))
                        .foregroundStyle(.placeholder)
                        .padding(.leading, 12)
                        .padding(.top, 12)
                        .allowsHitTesting(false)
                }
            }
            .frame(minHeight: 180)
            .background(Color(nsColor: .textBackgroundColor))
            .clipShape(RoundedRectangle(cornerRadius: 6))
            .overlay(
                RoundedRectangle(cornerRadius: 6)
                    .strokeBorder(Color(nsColor: .separatorColor), lineWidth: 1)
            )

            if let error = jsonHelperParseError {
                Label(error, systemImage: "exclamationmark.triangle.fill")
                    .font(.caption)
                    .foregroundStyle(.red)
            }
        }
    }

    @ViewBuilder
    private var syntaxReferencePopover: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Syntax Reference")
                .font(.headline)

            VStack(alignment: .leading, spacing: 4) {
                Group {
                    Text("key \"string\"      \u{2192} string")
                    Text("key 42            \u{2192} number")
                    Text("key true/false    \u{2192} boolean")
                    Text("key null          \u{2192} null")
                    Text("key               \u{2192} nested object")
                    Text("    child \"val\"     (indent children)")
                    Text("    - \"item\"      \u{2192} array")
                }
                .font(.system(.caption, design: .monospaced))
                .foregroundStyle(.secondary)
            }

            Divider()

            Text("Example")
                .font(.subheadline)
                .fontWeight(.medium)

            Text("""
                name "John Doe"
                age 30
                active true
                address
                    city "New York"
                tags
                    - "swift"
                """)
                .font(.system(.caption, design: .monospaced))

            HStack {
                Spacer()
                Button("Fill Example Data") {
                    jsonHelperText = JSONHelperParser.defaultExample
                    showExamplePopover = false
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.small)
            }
        }
        .padding()
        .frame(width: 300)
    }

    // MARK: - Detection & Validation

    private var detectedBodyType: String? {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        if trimmed.hasPrefix("{") || trimmed.hasPrefix("[") {
            return "JSON"
        } else if config.detectXML && trimmed.hasPrefix("<") {
            return "XML"
        }
        return "Text"
    }

    private func isBodyValid(for type: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard let data = trimmed.data(using: .utf8) else { return false }
        if type == "JSON" {
            return (try? JSONSerialization.jsonObject(with: data)) != nil
        } else if type == "XML" {
            return XMLParser(data: data).parse()
        }
        return true
    }

    private func bodyTypeBadgeColor(_ type: String) -> Color {
        switch type {
        case "JSON": return Color.blue.opacity(0.15)
        case "XML": return Color.orange.opacity(0.15)
        default: return Color.gray.opacity(0.15)
        }
    }

    private func bodyTypeForegroundColor(_ type: String) -> Color {
        switch type {
        case "JSON": return .blue
        case "XML": return .orange
        default: return .secondary
        }
    }

    // MARK: - Static Helpers

    static func isValidJSON(_ text: String) -> Bool {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, let data = trimmed.data(using: .utf8) else { return false }
        return (try? JSONSerialization.jsonObject(with: data)) != nil
    }
}
